[package]
name = "minions"
version = "0.1.0"
authors = ["BlahGeek <i@BlahGeek.com>"]

[features]
use-gtk = ["gtk", "gdk"]

[lib]
name = "minions"
path = "src/lib.rs"
doc = false

[[bin]]
name = "minions_gtk"
path = "src/bin/minions_gtk.rs"
required-features = ["use-gtk"]
doc = false

[[bin]]
name = "minions_rofi"
path = "src/bin/minions_rofi.rs"

[dependencies]
toml = "0.4.1"
serde = "1.0"
serde_derive = "1.0.8"
log = "0.3.7"
env_logger = "0.4.3"
lazy_static = "0.2.8"
rust-ini = "0.10.0"
shlex = "0.1.1"
url = "1.5.0"
gdk = { version = "0.5.2", optional = true }
gtk = { version = "0.1.2", features = ["v3_10"], optional = true }
