[package]
name = "minions"
version = "0.1.0"
authors = ["BlahGeek <i@BlahGeek.com>"]

[lib]
name = "minions"
path = "src/lib.rs"
doc = false

[[bin]]
name = "minions"
path = "src/bin/minions.rs"
doc = false

[dependencies]
gdk = "0.5.2"
rust-ini = "0.10.0"
shlex = "0.1.1"

[dependencies.gtk]
version = "0.1.2"
features = ["v3_10"]
