# default config for minions app

# List of directories containing extra plugins
extra_plugin_directories = [
]

[global]
    # Timeout (in milliseconds) to clear filter text if no more characters is entered
    # Set to 0 to disable
    filter_timeout = 800

    # Keyboard shortcuts to bring up Minions
    shortcut_show = "<Ctrl>space"
    # Keyboard shortcuts to bring up Minions with selected text
    shortcut_show_quicksend = "<Ctrl><Shift>space"

    # Hash salt used in history file
    # Change this value would make all histories invalid
    history_file_salt = "Minions-Salt"

# list of search engines
# Each site must have `name` and `address` defined
# and optionally `suggestion_url` for suggestions, which follows the OpenSearch standard
[search_engine]
    [[search_engine.sites]]
    name = "Google"
    address = "https://www.google.com/search?q=%s"
    [[search_engine.sites]]
    name = "Bing"
    address = "https://www.bing.com/search?q=%s"
    suggestion_url = "https://www.bing.com/osjson.aspx?query=%s"
    [[search_engine.sites]]
    name = "DuckDuckGo"
    address = "https://duckduckgo.com/?q=%s"
    suggestion_url = "https://ac.duckduckgo.com/ac/?q=%s&type=list"
    [[search_engine.sites]]
    name = "Wikipedia"
    address = "https://en.wikipedia.org/wiki/Special:Search?search=%s"
    suggestion_url = "https://en.wikipedia.org/w/api.php?action=opensearch&search=%s"

# Linux desktop entries (Applications)
[linux_desktop_entry]
# Directories to find all .desktop files
    directories = [
        "/usr/local/share/applications/",
        "/usr/share/applications/",
    ]

# File Browser
# Each entry must include a `name` and a valid `path` (can be directory or file)
[file_browser]
    [[file_browser.entries]]
    name = "Home Directory"
    path = "/home/"
    [[file_browser.entries]]
    name = "Root Directory"
    path = "/"


[clipboard_history]
    # Max number of recent entries to record in history
    max_entries = 64
    # Whether to ignore entries with only single byte (useful if you use vim and press "x" a lot)
    ignore_single_byte = true
