# default config for minions app

# Timeout (in milliseconds) to clear filter text if no more characters is entered
# Set to 0 to disable
filter_timeout = 800

extra_plugin_directories = [
]

[global_shortcuts]
show = "<Ctrl>space"
show_quicksend = "<Ctrl><Shift>space"

# list of search engines
[search_engine]
    [[search_engine.sites]]
    name = "Google"
    address = "https://www.google.com/search?q=%s"
    [[search_engine.sites]]
    name = "Bing"
    address = "https://www.bing.com/search?q=%s"
    suggestion_url = "https://www.bing.com/osjson.aspx?query=%s"
    [[search_engine.sites]]
    name = "DuckDuckGo"
    address = "https://duckduckgo.com/?q=%s"
    suggestion_url = "https://ac.duckduckgo.com/ac/?q=%s&type=list"
    [[search_engine.sites]]
    name = "Wikipedia"
    address = "https://en.wikipedia.org/wiki/Special:Search?search=%s"
    suggestion_url = "https://en.wikipedia.org/w/api.php?action=opensearch&search=%s"

[linux_desktop_entry]
directories = [
    "/usr/local/share/applications/",
    "/usr/share/applications/",
]

[file_browser]
    [[file_browser.entries]]
    name = "Home Directory"
    path = "/home/blahgeek/"
    [[file_browser.entries]]
    name = "Root Directory"
    path = "/"

[clipboard_history]
max_entries = 64
ignore_single_byte = true
